=== SmartRenaldo/Java-Foundation/Test6/TestXML/xml/books.dtd
<!ELEMENT bookshelf (book+)>
<!ELEMENT book (name, author, price, content)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT content (#PCDATA)>

=== SmartRenaldo/Java-Foundation/Test6/TestXML/xml/demo03_dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE bookshelf SYSTEM "books.dtd">
<bookshelf>
    <book>
        <name>Harry Potter</name>
        <author>J.K. Rowling</author>
        <price>55.99</price>
        <content>fly</content>
    </book>
    <book>
        <name>Black</name>
        <author>Mike</author>
        <price>expensive</price>
        <content>color</content>
    </book>
</bookshelf>
