=== SmartRenaldo/Java-Foundation/Test6/TestXML/xml/books02.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.itcast.cn2/xml"
        elementFormDefault="qualified">
    <!-- targetNamespace:申明约束文档的地址（命名空间）-->
    <!-- elementFormDefault:支持使用别名-->
    <element name="bookshelf">
        <!-- 写子元素 -->
        <complexType>
            <!-- maxOccurs='unbounded': 书架下的子元素可以有任意多个！-->
            <sequence maxOccurs="unbounded">
                <element name="book">
                    <!-- 写子元素的！ -->
                    <complexType>
                        <!-- 子元素必须有序-->
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="author" type="string"/>
                            <element name="price" type="decimal"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== SmartRenaldo/Java-Foundation/Test6/TestXML/src/demo04_schema.xml
<?xml version="1.0" encoding="UTF-8" ?>
<bookshelf xmlns="http://www.itcast.cn2/xml"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.itcast.cn2/xml ../xml/books02.xsd">
    <!--xmlns:it="http://www.itcast.cn/xml": 给引用的约束起前缀，用来控制当出现多个约束的时候使用的是哪一个-->
    <!--若没有多个约束，则应写成xmlns="http://www.itcast.cn/xml"-->
    <book>
        <name>java learning</name>
        <author>Yiqi Li</author>
        <price>444.44</price>
    </book>
    <book>
        <name>MySQL</name>
        <author>trump</author>
        <price>22.9</price>
    </book>
</bookshelf>
