=== SmartRenaldo/Java-Foundation/Test6/TestXML/xml/homework_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--作业3.	通过Schema在idea下写出对应的XML文件-->
<!--        	这是这个名为 "shoporder.xsd" 的 schema 文件的文档清单，写出它的XML文件-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.awesome.com/XMLDoc"
        elementFormDefault="qualified">
    <element name="shopOrder">
        <complexType>
            <sequence>
                <element name="goods" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="price" type="double"/>
                            <element name="number" type="integer"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
    <simpleType name="nameType">
        <restriction base="string">
            <pattern value="Walmart_\d{3}"/>
        </restriction>
    </simpleType>
</schema>

=== SmartRenaldo/Java-Foundation/Test6/TestXML/xml/homework_schema.xml
<?xml version="1.0" encoding="UTF-8" ?>
<shopOrder xmlns="http://www.awesome.com/XMLDoc"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.awesome.com/XMLDoc homework_schema.xsd">
    <goods>
        <name>bean</name>
        <price>55.55</price>
        <number>4</number>
    </goods>
    <goods>
        <name>beef</name>
        <price>33.555</price>
        <number>3</number>
    </goods>
</shopOrder>
